name: jl
on:
  workflow_dispatch:
  #schedule:
    #- cron: "3 0-8 * * *"
  watch:
    types: started
  repository_dispatch:
    types: jl
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【萌喵大作战】'
        run: |
          node Task/jl.js
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          JLKK_HD: ${{ secrets.JLKK_HD }}
          JLKKTX_HD: ${{ secrets.JLKKTX_HD }}