name: 腾讯自选股

on:
  workflow_dispatch:
  schedule:
     - cron: '39 8 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        TX_USERHEADER: ${{ secrets.TX_USERHEADER }}
        TX_USERKEY: ${{ secrets.TX_USERKEY }}        
        TX_SIGNHEADER: ${{ secrets.TX_SIGNHEADER }}
        TX_SIGNKEY: ${{ secrets.TX_SIGNKEY }}        
        TX_TASKHEADER: ${{ secrets.TX_TASKHEADER }}        
        TX_TASKKEY: ${{ secrets.TX_TASKKEY }}        
        TX_WXTASKKEY: ${{ secrets.TX_WXTASKKEY }}		
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/x101013416/123.git ~/123
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.TX_TASKHEADER
        run: |
          cd ~/123
          npm install
      - name: '运行 【腾讯自选股】'
        if: env.TX_TASKHEADER
        run: |
          cd ~/123
          node Task/txstock.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
