# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 中青看点

on:
  workflow_dispatch:
  schedule:
     - cron: '*/10 * * * *'
  watch:
    types: started
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
        
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        if: env.YOUTH_HEADER
        run: |
          npm install
      - name: '运行 【中青看点】'
        if: env.YOUTH_HEADER
        run: |
          node Task/youth.js
        env:
          YOUTH_HEADER: ${{ secrets.YOUTH_HEADER }}
          YOUTH_ARTBODY: ${{ secrets.YOUTH_ARTBODY }}
          YOUTH_TIME: ${{ secrets.YOUTH_TIME }}
          YOUTH_NOTIFY_CONTROL: ${{ secrets.YOUTH_NOTIFY_CONTROL }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
      - name: '运行 【中青看点2】'
        if: env.YOUTH_HEADER
        run: |
          node Task/youth.js
        env:
          YOUTH_HEADER: ${{ secrets.YOUTH_HEADER2 }}
          YOUTH_ARTBODY: ${{ secrets.YOUTH_ARTBODY2 }}
          YOUTH_TIME: ${{ secrets.YOUTH_TIME2 }}
          YOUTH_NOTIFY_CONTROL: ${{ secrets.YOUTH_NOTIFY_CONTROL }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}

    
