name: 芝麻视频

on:
    workflow_dispatch:
    schedule:
      - cron: "0 */1 * * *"
    watch:
      types: [started]
    repository_dispatch:
      types: zhima

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: pizile/BBB              

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【1】'
        run: |
          node Task/zhima.js
        env:
          ZM_zhimatxbody: ${{ secrets.ZM_zhimatxbody }}
          ZM_CASH: ${{ secrets.ZM_CASH }}
          ZM_zhimabody: ${{ secrets.ZM_zhimabody }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
